version: '3.1'

services:
  ngcash_front:
    container_name: ngcash_frontend
    build: ./frontend
    working_dir: /app-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app-frontend
    depends_on:
      ngcash_backend:
        condition: service_healthy
    networks:
      - web_network
    
  ngcash_backend:
    container_name: ngcash_server_backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
    - ./backend:/app-backend
    depends_on:
      ngcash_db:
        condition: service_healthy
    environment:
      - SERVER_PORT=3001
      - DB_HOST=ngcash_db
      - DB_NAME=ngcash_db
      - DB_USER=ngcash
      - DB_PASS=ngcash123
      - DB_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
    networks:
      - database_network
      - web_network

  ngcash_db:
    container_name: ngcash_database
    image: 'postgres'
    restart: always
    user: 'postgres'
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ngcash
      - POSTGRES_PASSWORD=ngcash123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ngcash_db -U ngcash"]
      timeout: 10s
      retries: 5
    networks:
      - database_network

networks:
  database_network:
  web_network: